run:
  concurrency: 3
  timeout: 15m
  issues-exit-code: 1
  tests: true

  skip-dirs:
    - data
  skip-files:

  # list of build tags, all linters use it. Default is empty list
  build-tags:
    - integration
# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: code-climate

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

  uniq-by-line: false

# all available settings of specific linters
linters-settings:
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/wimspaargaren/go-concurrency-examples)
  errcheck:
    check-type-assertions: false
    check-foonk: true
  govet:
    check-shadowing: false
  nestif:
    min-complexity: 10
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 18
  dupl:
    threshold: 175
  goconst:
    min-len: 3
    min-occurrences: 3
  funlen:
    lines: 80
    statements: 50
  godox:
    keywords:
      - HACK
      - OPTIMIZE
      - TODO
      - BUG
  misspell:
    locale: UK
    ignore-words:
      - color
      - realization
      - realized
      - realize
      - nationaal
      - transporteur
      - fulfillment
  unused:
    check-exported: false

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 0
  prealloc:
    simple: true
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: false # Report preallocation suggestions on for loops, false by default

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    # Disabled because of generics
    # - wastedassign
    # - rowserrcheck
  fast: false

severity: 
  default-severity: error
  rules:
    - linters:
        - gomodguard
      severity: warning

issues:
  exclude-rules:
    - path: _mock\.go
      linters:
        - gomnd
        - gocritic

    - path: _test\.go
      linters:
        - bodyclose
        - gocyclo
        - dupl
        - gosec
        - funlen
        - scopelint
        - goerr113

    - linters:
        - staticcheck
      text: "SA9003:"

    - linters:
        - lll
      text: "^//go:generate "

  exclude-use-default: true

  max-issues-per-linter: 0

  max-same-issues: 0

  new: false
